schema_version = 3
selected_device = "direct:046d:b034:serial:2443zbm0hda8"

[app_settings]
launch_at_login = true
check_for_updates = true
update_prompt_seen = true
show_in_menu_bar = true
auto_download_assets = true
thumbwheel_sensitivity = 14

[devices."direct:046d:b034:serial:2443zbm0hda8".identity]
display_name = "MX Master 3S"
codename = "Logitech MX Master 3S"
kind = "mouse"

[devices."direct:046d:b034:serial:2443zbm0hda8".identity.model_info]
entity_count = 3
unit_id = [
    0,
    0,
    0,
    0,
]
model_ids = [
    45108,
    0,
    0,
]
extended_model_id = 1

[devices."direct:046d:b034:serial:2443zbm0hda8".identity.model_info.transports]
usb = false
equad = false
btle = true
bluetooth = false

[devices."direct:046d:b034:serial:2443zbm0hda8".identity.capabilities]
buttons = true
pointer = true
lighting = false
scroll_inversion = true

[devices."receiver:cd289855cbbb8f03:slot:2"]
gesture_owner = "GestureButton"

[devices."receiver:cd289855cbbb8f03:slot:2".identity]
display_name = "MX Master 3S"
codename = "MX Master 3S"
kind = "mouse"

[devices."receiver:cd289855cbbb8f03:slot:2".identity.model_info]
entity_count = 3
unit_id = [
    0,
    0,
    0,
    0,
]
model_ids = [
    45108,
    0,
    0,
]
extended_model_id = 1

[devices."receiver:cd289855cbbb8f03:slot:2".identity.model_info.transports]
usb = false
equad = false
btle = true
bluetooth = false

[devices."receiver:cd289855cbbb8f03:slot:2".identity.capabilities]
buttons = true
pointer = true
lighting = false
scroll_inversion = true

[devices."receiver:cd289855cbbb8f03:slot:2".bindings]
Back = "MouseBack"
Forward = "MouseForward"

[devices."receiver:cd289855cbbb8f03:slot:2".bindings.MiddleClick]
Up = "MissionControl"
Down = "ShowDesktop"
Left = "PrevTab"
Right = "NextTab"
Click = "MiddleClick"

[devices."receiver:cd289855cbbb8f03:slot:2".bindings.GestureButton]
Up = "MissionControl"
Down = "ShowDesktop"
Left = "PrevTab"
Right = "NextTab"
Click = "AppExpose"
